var commonOptions = {};
commonOptions.apiKey = "<LoginRadius API Key>";
commonOptions.appName = "<LoginRadius App Name>";
commonOptions.hashTemplate= true;
commonOptions.sott ="<SOTT>";
var path = window.location.href;
commonOptions.verificationUrl = path.slice(0, path.lastIndexOf('/')).concat("/email-verification");
commonOptions.resetPasswordUrl = path.slice(0, path.lastIndexOf("/")).concat("/reset-password");
var LRObject= new LoginRadiusV2(commonOptions);
